name: clang-tidy

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: sudo apt-get install -yq clang-tidy

    - run: find include/ -src/ name '*.hpp' | xargs -I '{}' clang-tidy --quiet '{}' -- --std=c++17 -Iinclude -Iexternal/json/include -Iexternal/PEGTL/include
